#pragma once

//IMAGENES
#define IMG_GATITO 162 
#define IMG_PERRITO 163 //ultimo

// WND LOGIN
#define IMG_LOGO 100
#define LBL_USUARIO 101
#define TXT_USUARIO 102
#define LBL_PASS 103
#define TXT_PASS 104
#define BTN_ENTRAR 105

// WND AGENDA
#define ID_MDI_FIRSTCHILD 1
#define MENU_PERFIL 140
#define MENU_PERFIL_EDITARINFO 112
#define MENU_PERFIL_CONFIG 106
#define MENU_CITAS_NUEVA 107
#define MENU_CITAS_EDITAR 108
#define MENU_CITAS_CANCELAR 109
#define MENU_AGENDA_VER 110
#define MENU_SALIR 111
#define IDC_MAIN_MDI 113
#define MENUPERFIL_EDITAR 141
#define MENUPERFIL_CANCELAR 143
#define LV_AGENDA 142 
#define MENUPERFIL_GUARDAR 119
#define BTN_VERINFOCITA 145
#define LBL_AGENDA_ID 146
#define LBL_AGENDA_FECHA 147
#define LBL_AGENDA_HORA 148
#define LBL_AGENDA_NOMBRECLIENTE 149
#define LBL_AGENDAGRID 150
#define LBL_AGENDA_AGENDA 151
#define LBL_AGENDA_ACCIONES 152
#define BTN_EDITARCITA 153
#define BTN_CANCELARCITA 154
#define BTN_PAGINACION 156 
#define LBL_PAGINA_AGENDA 157
#define CBX_FILTRARPORFECHA 158
#define LBL_AGENDA_FILTRO 159
#define BTN_QUITARFILTRO 160

// WND CHILD INFO DOCTOR
#define TXT_CEDULADOCTOR 114
#define TXT_NOMBREDOCTOR 115
#define TXT_APELLIDODOCTOR 116
#define TXT_TELEFONODOCTOR 117
#define TXT_CORREODOCTOR 118
#define LBL_INFODOCTOR_ERROR 120
#define BTN_EDITARINFO 121
#define BTN_CANCELAREDICION 122
#define BTN_ELEGIRFOTODOCTOR 144

// WND CITA NUEVA
#define TXT_NUMEROCITA 122
#define DT_FECHACITA 123
#define DT_HORACITA 124
#define TXT_COSTOCITA 125
#define TXT_NOMBRECLIENTE 126
#define TXT_APELLIDOCLIENTE 127
#define TXT_TELEFONOCLIENTE 128
#define TXT_NOMBREMASCOTA 129
#define CB_ESPECIEMASCOTA 130
#define TXT_SEXOMASCOTA 131
#define RB_MACHOMASCOTA 132
#define RB_HEMBRAMASCOTA 133
#define BTN_REGISTRARCITA 134
#define TXT_MOTIVOCONSULTA 135
#define GRP_DATOSCITA 136
#define GRP_DATOSCLIENTE 137
#define GRP_DATOSMASCOTA 138
#define BTN_LIMPIARREGISTRARCITA 139
#define BTN_ACTUALIZARCITA 161 

//WND Resumen Cita
#define BTN_SALIRRESUMEN 155
#define LBL_RESUMEN_NUMCITA 156
#define LBL_RESUMEN_FECHA 157
#define LBL_RESUMEN_HORA 158
#define LBL_RESUMEN_COSTO 159
#define LBL_RESUMEN_MOTIVO 160
#define LBL_RESUMEN_NOMBRECLIENTE 161
#define LBL_RESUMEN_TELEFONO 162
#define LBL_RESUMEN_NOMBREMASCOTA 163
#define LBL_RESUMEN_ESPECIE 164
